services:
  order-service:
    build:
      context: ..
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "50051:50051"
    networks:
      - ecommerce-net
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://ecommerce:ecommerce@postgres:5432/ecommerce?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  payment-service:
    build:
      context: ..
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "50052:50052"
    networks:
      - ecommerce-net
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://ecommerce:ecommerce@postgres:5432/ecommerce?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  notification-service:
    build:
      context: ..
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "50053:50053"
    networks:
      - ecommerce-net
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-net
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  ecommerce-net:
    driver: bridge

volumes:
  pgdata:
